var App = require('./app');

App.Router.map(function() {

  // generated by ember-generate --scaffold
  this.resource('users');
  this.resource('user', {path: '/users/:user_id'});
  this.route('edit_user', {path: '/users/:user_id/edit'});
  this.route('new_user', {path: '/users/new'});
  // end generated routes


});

